#!/usr/bin/env python
from google.appengine.ext import db

class Pointers(db.Model):
  json              = db.TextProperty()
  pointer           = db.IntegerProperty(default=0)
  latestAlbum       = db.IntegerProperty(default=0)

class Albums(db.Model):
  id                = db.IntegerProperty(default=0)
  name              = db.StringProperty(default='')
  purchases         = db.IntegerProperty(default=0)
  cover             = db.StringProperty(default='')
  track1            = db.StringProperty(default='')
  track1name        = db.StringProperty(default='')
  track2            = db.StringProperty(default='')
  track2name        = db.StringProperty(default='')
  track3            = db.StringProperty(default='')
  track3name        = db.StringProperty(default='')
  track4            = db.StringProperty(default='')
  track4name        = db.StringProperty(default='')
  track5            = db.StringProperty(default='')
  track5name        = db.StringProperty(default='')
  track6            = db.StringProperty(default='')
  track6name        = db.StringProperty(default='')
  track7            = db.StringProperty(default='')
  track7name        = db.StringProperty(default='')
  track8            = db.StringProperty(default='')
  track8name        = db.StringProperty(default='')
  track9            = db.StringProperty(default='')
  track9name        = db.StringProperty(default='')
  track10           = db.StringProperty(default='')
  track10name       = db.StringProperty(default='')
  backfilled        = db.IntegerProperty(default=0)
  last_update       = db.DateTimeProperty(auto_now_add=True, required=True)
